# Copyright (c) 2022-2025, The Isaac Lab Project Developers.
# Copyright (c) 2025-2026, The RoboLab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

import os

import isaaclab.sim as sim_utils
import isaaclab.terrains as terrain_gen
from isaaclab.managers import SceneEntityCfg
from isaaclab.terrains import TerrainGeneratorCfg
from isaaclab.utils import configclass

from robolab import ROBOLAB_ROOT_DIR
from robolab.assets.robots.roboparty import BUMI_CFG, BUMI_STANDING_ROOT_HEIGHT
from robolab.tasks.manager_based.amp.rpo_amp_env_cfg import AMP_NUM_STEPS, RPOAmpEnvCfg


BUMI_AMP_KEY_BODY_NAMES = [
    "l_ankle_roll_link",
    "r_ankle_roll_link",
    "l_knee_pitch_link",
    "r_knee_pitch_link",
    "l_elbow_pitch_link",
    "r_elbow_pitch_link",
]

BUMI_AMP_FLAT_TERRAIN_CFG = TerrainGeneratorCfg(
    curriculum=False,
    size=(256.0, 256.0),
    border_width=0.0,
    num_rows=1,
    num_cols=1,
    horizontal_scale=0.1,
    vertical_scale=0.005,
    use_cache=False,
    sub_terrains={
        "flat": terrain_gen.MeshPlaneTerrainCfg(proportion=1.0),
    },
)


@configclass
class BumiAmpEnvCfg(RPOAmpEnvCfg):
    def __post_init__(self):
        super().__post_init__()

        self.scene.robot = BUMI_CFG.replace(prim_path="{ENV_REGEX_NS}/Robot")
        # Avoid blocking scene creation on remote Nucleus visual assets.
        self.scene.sky_light.spawn.texture_file = None
        self.scene.terrain.visual_material = sim_utils.PreviewSurfaceCfg(
            diffuse_color=(0.25, 0.25, 0.25),
        )
        self.scene.terrain.terrain_type = "generator"
        self.scene.terrain.terrain_generator = BUMI_AMP_FLAT_TERRAIN_CFG
        self.scene.robot.init_state.pos = (0.0, 0.0, BUMI_STANDING_ROOT_HEIGHT)
        # bumi_lab data is regenerated by scripts/tools/retarget/rpo_to_bumi_motion.py:
        # joints are range-mapped to Bumi and key bodies are rebuilt from Bumi FK.
        self.motion_data.motion_dataset.motion_data_dir = os.path.join(
            ROBOLAB_ROOT_DIR, "data", "motions", "bumi_lab"
        )
        self.animation.animation.num_steps_to_use = AMP_NUM_STEPS
        self.observations.disc.key_body_pos_b.params = {
            "asset_cfg": SceneEntityCfg(
                name="robot",
                body_names=BUMI_AMP_KEY_BODY_NAMES,
                preserve_order=True,
            )
        }

        self.events.add_base_mass.params["asset_cfg"].body_names = "base_link"
        self.events.randomize_rigid_body_com.params["asset_cfg"].body_names = ["base_link", "waist_yaw_link"]
        self.events.scale_link_mass.params["asset_cfg"].body_names = ["l_.*_link", "r_.*_link"]
        self.events.base_external_force_torque.params["asset_cfg"].body_names = "waist_yaw_link"
        self.events.reset_robot_joints.params["position_range"] = (0.95, 1.05)

        self.rewards.feet_distance_y.params["asset_cfg"] = SceneEntityCfg(
            "robot",
            body_names=["l_ankle_roll_link", "r_ankle_roll_link"],
            preserve_order=True,
        )
        # Bumi default-pose feet separation is 0.199 m (RPO: 0.145 m); shift the
        # acceptance band up and keep the demo-scaled stride range in reach.
        self.rewards.feet_distance_y.params["min"] = 0.16
        self.rewards.feet_distance_y.params["max"] = 0.50
        # Enforce left-right gait/arm symmetry while still allowing anti-phase swing.
        self.rewards.arm_pitch_mean_offset.weight = -0.1
        self.rewards.leg_sagittal_pair_symmetry.weight = -0.10
        self.rewards.arm_pair_symmetry.weight = -0.20
        self.rewards.hip_roll_yaw_pair_symmetry.weight = -0.08
        self.rewards.undesired_contacts.params["sensor_cfg"] = SceneEntityCfg(
            "contact_forces",
            body_names=["(?!.*ankle.*).*"],
        )

        # Velocity commands must stay inside what the retargeted Bumi demo data
        # covers (fastest run ~3.0 m/s after 0.73 height scaling) and what the
        # smaller actuators can track; RPO's (-0.5, 2.5) is kept but trimmed at
        # the top to avoid commanding beyond the demo distribution.
        self.commands.base_velocity.ranges.lin_vel_x = (-0.5, 2.0)
        self.commands.base_velocity.ranges.lin_vel_y = (-0.4, 0.4)
        self.commands.base_velocity.ranges.ang_vel_z = (-1.2, 1.2)
        self.commands.base_velocity.debug_vis = False
        self.terminations.base_contact.params["sensor_cfg"].body_names = [
            "base_link",
            "waist_yaw_link",
            ".*_leg_.*_link",
            ".*_arm_.*_link",
            ".*_elbow_pitch_link",
        ]
        self.disable_zero_weight_rewards()


@configclass
class BumiAmpEnvCfg_PLAY(BumiAmpEnvCfg):
    def __post_init__(self):
        super().__post_init__()

        self.scene.num_envs = 1
        self.scene.env_spacing = 2.5
        self.episode_length_s = 40.0

        self.commands.base_velocity.ranges.lin_vel_x = (1.0, 1.0)
        self.commands.base_velocity.ranges.lin_vel_y = (0.0, 0.0)
        self.commands.base_velocity.ranges.ang_vel_z = (0.0, 0.0)

        self.observations.policy.enable_corruption = False
        self.events.push_robot = None
        self.events.reset_robot_joints.params["position_range"] = (1.0, 1.0)
        self.events.reset_robot_joints.params["velocity_range"] = (0.0, 0.0)
        self.events.reset_base.params["pose_range"] = {
            "x": (0.0, 0.0),
            "y": (0.0, 0.0),
            "yaw": (0.0, 0.0),
        }
        self.events.reset_base.params["velocity_range"] = {
            "x": (0.0, 0.0),
            "y": (0.0, 0.0),
            "z": (0.0, 0.0),
            "roll": (0.0, 0.0),
            "pitch": (0.0, 0.0),
            "yaw": (0.0, 0.0),
        }
